/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.dao.OrcamentoDAO;
import model.dao.readMais;

public class Main extends javax.swing.JFrame {
   NovoCliente nc = new NovoCliente();
   NovoOrcamento no = new NovoOrcamento();
   NovoProduto np = new NovoProduto();
   viewOrcamento vo = new viewOrcamento();
   int i = 0;
   
    public Main() {
        initComponents(); 
        readTable();
        readTableRecestes();
    }
    public void readTable(){
        DefaultTableModel modelo = (DefaultTableModel) jTableproMaisvendidos.getModel();
        modelo.setNumRows(0);
        readMais rMais = new readMais();
        rMais.read().stream().forEach((c) -> {
            modelo.addRow(new Object[]{
                c.getQtd(),
                c.getNomeProduto(),
                c.getPrecoProduto(),
            });
        });
        
    }
    public void readTableRecestes(){

        DefaultTableModel modelo = (DefaultTableModel) jTableRecestes.getModel();
        modelo.setNumRows(0);
        OrcamentoDAO rdao = new OrcamentoDAO();
        rdao.read().stream().forEach((c) ->{
            modelo.addRow(new Object[]{
                c.getNomeCliente(),
                c.getTituloOrcamento(),
                c.getIdOrcamento(),
            });
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDesktopPaneMain = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableproMaisvendidos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableRecestes = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuINVCLIENTE = new javax.swing.JMenuItem();
        jMenuNVPRODUTO = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuNOVOORCAMENTO = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setName(""); // NOI18N

        jDesktopPaneMain.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jDesktopPaneMain.setName(""); // NOI18N

        javax.swing.GroupLayout jDesktopPaneMainLayout = new javax.swing.GroupLayout(jDesktopPaneMain);
        jDesktopPaneMain.setLayout(jDesktopPaneMainLayout);
        jDesktopPaneMainLayout.setHorizontalGroup(
            jDesktopPaneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 861, Short.MAX_VALUE)
        );
        jDesktopPaneMainLayout.setVerticalGroup(
            jDesktopPaneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPaneMain)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPaneMain)
                .addContainerGap())
        );

        jTableproMaisvendidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Quantidade", "Nome Produto", "Preço Produto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableproMaisvendidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableproMaisvendidosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTableproMaisvendidos);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Produtos mais visados");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Orçamentos Recentes");

        jTableRecestes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Clinte", "Titulo", "ID Orçamento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableRecestes);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        jMenu1.setText("Cadastrar ");

        jMenuINVCLIENTE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user_add.png"))); // NOI18N
        jMenuINVCLIENTE.setText("Cliente");
        jMenuINVCLIENTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuINVCLIENTEActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuINVCLIENTE);

        jMenuNVPRODUTO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/package_add.png"))); // NOI18N
        jMenuNVPRODUTO.setText("Produto");
        jMenuNVPRODUTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuNVPRODUTOActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuNVPRODUTO);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/application.png"))); // NOI18N
        jMenu2.setText("Orçamento");

        jMenuNOVOORCAMENTO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/application_add.png"))); // NOI18N
        jMenuNOVOORCAMENTO.setText("Novo Orçamento");
        jMenuNOVOORCAMENTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuNOVOORCAMENTOActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuNOVOORCAMENTO);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addComponent(jLabel2)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuINVCLIENTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuINVCLIENTEActionPerformed
        nc.setVisible(false);
        np.setVisible(false);
        no.setVisible(false);
        jDesktopPaneMain.removeAll();
        setDefaultCloseOperation(np.EXIT_ON_CLOSE);
        setDefaultCloseOperation(nc.EXIT_ON_CLOSE);
        setDefaultCloseOperation(no.EXIT_ON_CLOSE);
        jDesktopPaneMain.add(nc);
        nc.setLocation(100, 50);
        nc.setVisible(true);

    }//GEN-LAST:event_jMenuINVCLIENTEActionPerformed

    private void jTableproMaisvendidosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableproMaisvendidosKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableproMaisvendidosKeyReleased

    private void jMenuNVPRODUTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuNVPRODUTOActionPerformed
        nc.setVisible(false);
        np.setVisible(false);
        no.setVisible(false);
        jDesktopPaneMain.removeAll();
        setDefaultCloseOperation(np.EXIT_ON_CLOSE);
        setDefaultCloseOperation(nc.EXIT_ON_CLOSE);
        setDefaultCloseOperation(no.EXIT_ON_CLOSE);
        jDesktopPaneMain.add(np);
        np.setLocation(100, 50);
        np.setVisible(true);

    }//GEN-LAST:event_jMenuNVPRODUTOActionPerformed

    private void jMenuNOVOORCAMENTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuNOVOORCAMENTOActionPerformed
        nc.setVisible(false);
        np.setVisible(false);
        no.setVisible(false);
        jDesktopPaneMain.removeAll();
        setDefaultCloseOperation(np.EXIT_ON_CLOSE);
        setDefaultCloseOperation(nc.EXIT_ON_CLOSE);
        setDefaultCloseOperation(no.EXIT_ON_CLOSE);
        jDesktopPaneMain.add(no);
        no.setLocation(100, 50);
        no.setVisible(true);

    }//GEN-LAST:event_jMenuNOVOORCAMENTOActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        this.setExtendedState(MAXIMIZED_BOTH);
        readTable();
        readTableRecestes(); 
   
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
     int rps;
     readTable();
        readTableRecestes();
     if(jTableRecestes.getSelectedRow() != -1){
         rps =2;
         do{
        i = Integer.parseInt(jTableRecestes.getValueAt(jTableRecestes.getSelectedRow(),2).toString());
        JOptionPane.showMessageDialog(null, i);
        rps=3;
         }while(rps!=3);
         
     }

        
        
        
        
         
    }//GEN-LAST:event_formWindowActivated

    /**jTable1.getValueAt(jTable1.getSelectedRow(),1).toString());
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPaneMain;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuINVCLIENTE;
    private javax.swing.JMenuItem jMenuNOVOORCAMENTO;
    private javax.swing.JMenuItem jMenuNVPRODUTO;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableRecestes;
    private javax.swing.JTable jTableproMaisvendidos;
    // End of variables declaration//GEN-END:variables
}
