
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.bean.Cliente;
import model.dao.ClienteDAO;
public class NovoCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form NovoCliente
     */
    public NovoCliente() {
        initComponents();
        readJTable();
        NovoCliente.setDefaultLocale(null);    
    }
     public void readJTable(){
        DefaultTableModel modelo = (DefaultTableModel) jTClientes.getModel();
        modelo.setNumRows(0);
        ClienteDAO cdao = new ClienteDAO();
        cdao.read().stream().forEach((c) -> {
        modelo.addRow(new Object[]{
                c.getId(),
                c.getNomeCliente(),
                c.getFoneCliente(),
                c.getEmailCliente(),
            });
        });   
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextnomeCliente = new javax.swing.JTextField();
        jTextfoneCliente = new javax.swing.JTextField();
        jTextemailCliente = new javax.swing.JTextField();
        jButtonCadastrarCliente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTClientes = new javax.swing.JTable();
        jButtonAtualizarCliente = new javax.swing.JButton();
        jButtonDeletarCliente = new javax.swing.JButton();

        setBorder(null);
        setClosable(true);
        setTitle("Novo Cliente");
        setAlignmentX(30.0F);
        setAlignmentY(200.0F);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user_add.png"))); // NOI18N

        jButtonCadastrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user_add.png"))); // NOI18N
        jButtonCadastrarCliente.setText("Cadastrar!");
        jButtonCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarClienteActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome Cliente:");

        jLabel2.setText("Fone Cliente:");

        jLabel3.setText("Email Cliente:");

        jTClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "FONE", "EMAIL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTClientesMouseClicked(evt);
            }
        });
        jTClientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTClientesKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTClientes);

        jButtonAtualizarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user_edit.png"))); // NOI18N
        jButtonAtualizarCliente.setText("Atualizar!");
        jButtonAtualizarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarClienteActionPerformed(evt);
            }
        });

        jButtonDeletarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user_delete.png"))); // NOI18N
        jButtonDeletarCliente.setText("Excluir!");
        jButtonDeletarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCadastrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAtualizarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDeletarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextfoneCliente)
                            .addComponent(jTextnomeCliente)
                            .addComponent(jTextemailCliente)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextnomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextfoneCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextemailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastrarCliente)
                    .addComponent(jButtonAtualizarCliente)
                    .addComponent(jButtonDeletarCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(457, 584));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarClienteActionPerformed
        Cliente c = new Cliente();
        ClienteDAO dao = new ClienteDAO();

        c.setNomeCliente(jTextnomeCliente.getText());
        c.setFoneCliente(jTextfoneCliente.getText());
        c.setEmailCliente(jTextemailCliente.getText());
        dao.create(c);
        readJTable();
        jTextnomeCliente.setText("");
        jTextemailCliente.setText("");
        jTextfoneCliente.setText("");
    }//GEN-LAST:event_jButtonCadastrarClienteActionPerformed

    private void jTClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTClientesMouseClicked
        if(jTClientes.getSelectedRow() != -1){
            jTextnomeCliente.setText(jTClientes.getValueAt(jTClientes.getSelectedRow(),1).toString());
            jTextfoneCliente.setText(jTClientes.getValueAt(jTClientes.getSelectedRow(),2).toString());
            jTextemailCliente.setText(jTClientes.getValueAt(jTClientes.getSelectedRow(),3).toString());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTClientesMouseClicked

    private void jTClientesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTClientesKeyReleased
        if(jTClientes.getSelectedRow() != -1){
            jTextnomeCliente.setText(jTClientes.getValueAt(jTClientes.getSelectedRow(),1).toString());
            jTextfoneCliente.setText(jTClientes.getValueAt(jTClientes.getSelectedRow(),2).toString());
            jTextemailCliente.setText(jTClientes.getValueAt(jTClientes.getSelectedRow(),3).toString());
        }
    }//GEN-LAST:event_jTClientesKeyReleased

    private void jButtonAtualizarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarClienteActionPerformed
        if(jTClientes.getSelectedRow() !=-1)
        {
            Cliente c = new Cliente();
            ClienteDAO dao = new ClienteDAO();

            c.setNomeCliente(jTextnomeCliente.getText());
            c.setFoneCliente(jTextfoneCliente.getText());
            c.setEmailCliente(jTextemailCliente.getText());
            c.setId((int)jTClientes.getValueAt(jTClientes.getSelectedRow(),0));
            dao.update(c);
            readJTable();
            jTextnomeCliente.setText("");
            jTextemailCliente.setText("");
            jTextfoneCliente.setText("");
        }
    }//GEN-LAST:event_jButtonAtualizarClienteActionPerformed

    private void jButtonDeletarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletarClienteActionPerformed
        if(jTClientes.getSelectedRow() != -1){
            Cliente c = new Cliente();
            ClienteDAO dao = new ClienteDAO();

            c.setId((int)jTClientes.getValueAt(jTClientes.getSelectedRow(),0));
            dao.delete(c);
            readJTable();
            jTextnomeCliente.setText("");
            jTextemailCliente.setText("");
            jTextfoneCliente.setText("");
        }else{
            JOptionPane.showMessageDialog(null, "Selecioone um Produto para Excluir");
        }
       
    }//GEN-LAST:event_jButtonDeletarClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtualizarCliente;
    private javax.swing.JButton jButtonCadastrarCliente;
    private javax.swing.JButton jButtonDeletarCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTClientes;
    private javax.swing.JTextField jTextemailCliente;
    private javax.swing.JTextField jTextfoneCliente;
    private javax.swing.JTextField jTextnomeCliente;
    // End of variables declaration//GEN-END:variables
}
